### ISSUE TITLE
UDP post

### ISSUE THREAD

**Issue by pioneersteffen** [kilianknoll/DWDForecast#2]
Hi Kilian, 

Great work! Many thanks! 

Would it be possible to push the results via UDP? It would be great to use it in my homeserver / smart home. 

Many thanks.

Best Regards 
Steffen

**Comment by kilianknoll** [comment]
Hi Steffen
I wanted to keep this script "simple" ;-) and not overload it too much with more functions (we already have print, csv - and database output). 
Also I treat UDP as some sort of realtime - trigger and forget protocol. But since the data from DWD are getting updated approx. every 3 times a day only, I am super hesitant to add this additional feature.
I will leave the issue open for now -maybe you provide some compelling reasons ;-) 

Best

Kilian

**Comment by kilianknoll** [comment]
Have not heard back - so will close this issue.
